site_name: The Cookbook
extra_css:
  - stylesheets/extra.css
  - stylesheets/grid.css

nav:
  - ...
  # - Home: index.md
  # - Breakfast:
  #   - breakfasts/index.md
  # - Main Dishes:
  #   - main_dishes/index.md
  # - Snacks:
  #   - snacks/index.md
  # - Dessert:
  #   - desserts/index.md
  - Reference:
    - reference/index.md
    - reference/calculator.md
    - reference/development.md
    - reference/equivalents_and_substitutes.md
    - reference/measuring.md
    - reference/seasons.md
    - reference/temperatures.md
  - Recipe Template: template_recipe.md
  - Tags: tags.md


plugins:
  - tags:
      tags_file: tags.md
  - search
  - git-revision-date-localized:
      strict: false
  - glightbox
  - mkdocs-video
  - awesome-pages

repo_url: https://github.com/baky0905/cookbook
repo_name: cookbook
edit_uri: edit/main/docs/

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

theme:
  name: material
  palette:
    - scheme: default
      primary: white
      accent: teal
    # media: "(prefers-color-scheme: light)"

      # toggle:
      #   icon: material/lightbulb
      #   name: Switch to dark mode
    # - media: "(prefers-color-scheme: dark)"
    #   scheme: slate
    #   primary: 'red'
    #   accent: 'amber'
    #   toggle:
    #     icon: material/lightbulb-outline
    #     name: Switch to light mode
  icon:
    annotation: material/information-variant-circle
    repo: fontawesome/brands/github
    logo: fontawesome/solid/pizza-slice
  features:
    - content.action.view
    - content.action.edit
    - content.tabs.link
    - content.code.copy
    - content.code.annotate
    - content.code.select
    - navigation.footer: false
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - toc.follow
    - search.highlight
    - search.share
    - search.suggest
  favicon: assets/favicon.ico
  theme:
  font:
    text: Nunito
    code: Roboto Mono
# copyright: Made by Kris
extra:
  search:
    language: en
  status:
    wip: Work In Progress
  generator: false

markdown_extensions:
  - abbr
  - toc:
      permalink: True
      toc_depth: 3
  - admonition
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      use_pygments: true
      linenums: false
      auto_title: true
      linenums_style: pymdownx-inline
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - def_list
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
